import NavBar from "./components/NavBar";
import "./globals.css";
import { Inter, Orbitron } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-orbitron" });

export const metadata = {
  title:{default : "Indie Gamer" , template : "%s | Indie Gamer"},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orbitron.variable}>
      <body className="flex flex-col min-h-screen bg-orange-200 px-4 py-4">
        <NavBar />
        <main className="grow">{children}</main>
        <footer className="text-center py-2 border-t border-slate-400">
          Image Curtesy by <a className="text-green-500 hover:text-" href="https://rawg.io/" target="__blank">Rawg</a>
        </footer>
      </body>
    </html>
  );
}
